version: "3.2"
services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    #user: 1000:1000 # should be owner of volumes
    ports:
      - "4040:4533"
    restart: unless-stopped
    depends_on: 
      pcloud:
        condition: service_healthy
    volumes:
      - type: volume
        source: navidrome-config
        target: /data
      - type: bind 
        source: "${HOST_PCLOUD_MNT_FOLDER}/${PCLOUD_MUSIC_FOLDER}"
        target: /music
        read_only: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    healthcheck:
      test: ["CMD", "ls", "/music"]
      interval: 10s
      timeout: 1s
      retries: 12
  pcloud:
    image: zcalusic/pcloud
    container_name: pcloud
    privileged: true
    restart: unless-stopped
    volumes:
      - pcloud-cache-dir:/root/.pcloud
      - ${HOST_PCLOUD_MNT_FOLDER}:/mnt/pcloud-data:shared
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    command: pcloudcc -u ${PCLOUD_ACCOUNT_EMAIL} -s -m /mnt/pcloud-data
    healthcheck:
      test: ["CMD", "ls", "/mnt/pcloud-data/${PCLOUD_MUSIC_FOLDER}"]
      interval: 10s
      timeout: 3s
      retries: 1 #2
  autoheal:
    restart: always
    image: willfarrell/autoheal
    container_name: autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
        #- AUTOHEAL_INTERVAL=60
        #- AUTOHEAL_START_PERIOD=120
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  pcloud-cache-dir:
  navidrome-config:
