version: "3.2"
services:
  navidrome:
    image: deluan/navidrome:0.54.3
    container_name: navidrome
    ports:
      - "4040:4533"
    restart: unless-stopped
    environment:
      ND_DEVACTIVITYPANEL: "false"
      ND_SCANSCHEDULE: "@daily"
      ND_ENABLEFAVOURITES: "false"
    depends_on:
      pcloud:
        condition: service_healthy
    volumes:
      - type: volume
        source: navidrome-config
        target: /data
      - type: bind
        source: "${HOST_PCLOUD_MNT_FOLDER}/${PCLOUD_MUSIC_FOLDER}"
        target: /music
        read_only: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    healthcheck:
      test: ["CMD", "ls", "/music"]
      interval: 10s
      timeout: 3s
      retries: 6
  pcloud:
    image: pgoellnitz/pcloud_2fa
    container_name: pcloud
    privileged: true
    restart: unless-stopped
    volumes:
      - pcloud-cache-dir:/root/.pcloud
      - ${HOST_PCLOUD_MNT_FOLDER}:/mnt/pcloud-data:shared
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    command: pcloudcc -u ${PCLOUD_ACCOUNT_EMAIL} -s -m /mnt/pcloud-data
    healthcheck:
      test: ["CMD", "ls", "/mnt/pcloud-data/${PCLOUD_MUSIC_FOLDER}"]
      interval: 10s
      timeout: 3s
      retries: 3
  autoheal:
    restart: always
    image: willfarrell/autoheal:1.2.0
    container_name: autoheal
    environment:
      AUTOHEAL_CONTAINER_LABEL: all
      AUTOHEAL_INTERVAL: 60
      AUTOHEAL_START_PERIOD: 120
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  pcloud-cache-dir:
  navidrome-config:
